0xsequence/web-sdk

packages/checkout/src/shared/styles.css.ts
packages/connectors/src/defaultConnectors.tsx
packages/kit/src/components/KitProvider/ConnectWalletContent/ExtendedWalletList.tsx
packages/kit/src/components/KitProvider/ConnectWalletContent/index.tsx
packages/kit/src/components/KitProvider/index.tsx
packages/kit/src/components/styles.css.ts
packages/kit/src/utils/getKitConnectWallets.ts
packages/wallet/src/shared/NavigationHeader/index.tsx
packages/wallet/src/shared/WalletHeader/index.tsx
packages/wallet/src/shared/styles.css.ts

Shows EIP6963 discovered wallets.

EIP6963 discovered wallets

---

examples/next/src/app/components/Connected.tsx
examples/react/src/components/Homepage.tsx

closes https://github.com/0xsequence/issue-tracker/issues/2437

rename embedded wallet option to inventory

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/checkout/src/hooks/useCheckoutWhitelistStatus.ts
packages/connectors/CHANGELOG.md
packages/connectors/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

- Added ability to disabled the useCheckoutWhitelistStatus hook
- vesion bump

Release 2.8.6

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/checkout/src/index.ts
packages/connectors/CHANGELOG.md
packages/connectors/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

- Export util for generating transak link
- release 2.8.10

Export transak link utils + release 2.8.10

---

packages/kit/src/components/KitProvider/ConnectWalletContent/index.tsx

https://github.com/0xsequence/issue-tracker/issues/2736

Email sign in was moved to a sign in tile rather than immediately showing the email input

---

README.md
examples/components/package.json
examples/components/src/Header.tsx
examples/next/package.json
examples/next/src/config.ts
examples/react/package.json
examples/react/src/config.ts
packages/checkout/package.json
packages/kit/README.md
packages/kit/package.json
packages/kit/src/chains/index.ts
packages/kit/src/config/defaultChains.ts
packages/kit/src/hooks/useChain.ts
packages/kit/src/index.ts
packages/wallet/package.json
pnpm-lock.yaml

```typescript
const chains = getDefaultChains() // Full list of sequence supported chains
```
or when only needing a subset
```typescript
const chains = getDefaultChains([ChainId.MAINNET, ChainId.POLYGON])
```

getDefaultChains: default sequence supported chains

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

Version bump to 2.11.1
new package version includes the separation of the connect wallet content into it's own component.

version bump 2.11.1

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

release 2.11.2 which includes a new component for sequence kit previews in Builder

release 2.11.2

---

packages/checkout/src/views/PendingTransaction.tsx

update iframe url for nft checkout. This will fix issues with the ublock ad blocker extension

update iframe url for nft checkout

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

- includes new changes related to new url endpoint for nft checkout

kit new release 2.11.3

---

examples/next/CHANGELOG.md
examples/next/package.json
examples/react/CHANGELOG.md
examples/react/package.json
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/checkout/src/shared/components/NavigationHeader.tsx
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

- fix visual bug which occurs in nft checkout demo

nft checkout navigation header fix +  new release 2.11.4

---

examples/components/package.json
examples/next/package.json
examples/react/package.json
packages/checkout/package.json
packages/checkout/src/views/TransferToWallet/QRCode.tsx
packages/kit/package.json
packages/kit/src/components/KitPreviewProvider/KitPreviewProvider.tsx
packages/kit/src/components/KitProvider/KitProvider.tsx
packages/kit/src/connectors/wagmiConnectors/sequenceConnector.ts
packages/kit/src/contexts/Analytics.ts
packages/kit/src/utils/ethAuth.ts
packages/wallet/package.json
packages/wallet/src/shared/SelectButton/SelectButton.tsx
packages/wallet/src/utils/helpers.ts
packages/wallet/src/views/Receive.tsx
pnpm-lock.yaml

Clean up deps

---

packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx

Show the main currency option before the swap quotes are loaded.
https://www.loom.com/share/6b6bf3175ec04534a1ca31d55de35a4c?sid=a41b8b7f-bd19-40e5-9c7d-96b79938a65b

Payment Modal: Swap quotes loading separate from maincurrency

---

examples/react/src/components/Connected.tsx
packages/checkout/src/contexts/SelectPaymentModal.ts
packages/checkout/src/hooks/useSelectPaymentModal.ts
packages/checkout/src/views/PaymentSelection/Footer.tsx
packages/checkout/src/views/PaymentSelection/ItemDescription/index.tsx
packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx
packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx
packages/checkout/src/views/PaymentSelection/index.tsx

Changes to the payment modal settings as preparation for integration into the marketplace boilerplate.
- allow multiple collectibles to be displayed
- credit card providers is an array in order to work with the marketplace api checkout endpoint

updated credit card settings for integration

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

Release 4.0.6 for sequence kit, which includes the payment selection modal

release version 4.0.6

---

packages/checkout/src/shared/components/KitCheckoutProvider.tsx
packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx
packages/checkout/src/views/PaymentSelection/index.tsx

- Fix for swap quotes params
- Styling for scrollbars

Sequence Pay fixes

---

packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx
packages/checkout/src/views/PaymentSelection/index.tsx
packages/kit/src/utils/transactions.ts

- Show message on the sequence pay modal if the transaction failed
- Fixed WaaS when the initial network is not the same as the one from the checkout

Sequence Pay: fixes

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/checkout/src/views/PaymentSelection/index.tsx
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

Fix for selection modal, new release

fix for kit + new release

---

packages/kit/src/components/Connect/Connect.tsx
packages/kit/src/connectors/wagmiConnectors/sequenceWaasConnector.ts

Fixed the saving of the waas signin email when loging in through waas email.

waas signin email fix for email login

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

- Added swap modal
- Added transaction status modal

release 4.4.4

---

packages/checkout/src/shared/components/NavigationHeader.tsx

Bug fix for header which would go out of the modal in some situations

bug fix for header

---

packages/kit/src/config/defaultConnectors.ts
packages/kit/src/connectors/walletConnect/walletConnect.ts

Fixes the issue where WalletConnect connector doesn't connect to the expected chain.
https://github.com/user-attachments/assets/5902a066-1f86-4ac3-8905-96ce98f79f69

Fix WalletConnect initial chain issue

---

examples/react/src/components/Connected.tsx
packages/checkout/package.json
packages/checkout/src/contexts/CheckoutModal.ts
packages/checkout/src/contexts/SelectPaymentModal.ts
packages/checkout/src/shared/components/KitCheckoutProvider.tsx
packages/checkout/src/utils/transak.ts
packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx
packages/checkout/src/views/index.ts
pnpm-lock.yaml

transak nft checkout

---

packages/checkout/src/views/PaymentSelection/OrderSummary/index.tsx

payment modal collectible quantity display fix

---

CODEOWNERS

Added @0xsequence-bot as first code owner to suppress notifications.

CODEOWNERS, suppress notifications

---

packages/checkout/src/contexts/AddFundsModal.ts
packages/checkout/src/utils/transak.ts

Use the debug environment variable to enable the debug mode

transak staging environment enable with the debug env variable

---

examples/next/src/app/components/Connected.tsx
examples/react/src/components/Connected.tsx

Cleanup demo options that are specific

clean up kit demo options

---

packages/checkout/src/views/PaymentSelection/TransferFunds.tsx

Fixed issue of QR code being too small by making a modal show up on click.
https://www.loom.com/share/8a1d1a8abb494d86884ffe929218b465?sid=98628fa9-153a-4495-908e-9c4c6a381a13

qr code fixes

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

-release 4.5.7 contains changes related to QR code in nft checkout modal

release 4.5.7

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

release 4.5.9

---

packages/checkout/src/constants/index.ts
packages/checkout/src/views/PaymentSelection/index.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx

Added databeat events for nft checkout

databeat for nft checkout

---

packages/kit/src/components/Connect/Connect.tsx
packages/kit/src/components/Connect/EmailWaasVerify.tsx
packages/kit/src/hooks/useWaasEmailAuth.ts

improvements to the OTP flow.
https://www.loom.com/share/4414d24e7e9f47c7bef49e60bebe9653?sid=ee741350-d9db-4272-aa04-2617224bf609

OTP flow improvements

---

packages/checkout/README.md

Updated documentation related to kit checkout

kit checkout docs update

---

packages/checkout/src/views/Swap/index.tsx
packages/wallet/src/views/SwapCoin/SwapList.tsx

Added error states for queries performed in the swap modal

error states swap modal

---

packages/kit/src/utils/transactions.ts

The fee selection process now takes into account the amount of owned tokens by the user.

fee options selection based on user balance for send transactions method

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

release 4.6.3

---

packages/kit/src/utils/transactions.ts

fix for sponsored transactions

sponsored tx fix

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/kit/CHANGELOG.md
packages/kit/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

Contains fix for sponsored transactions in WaaS (issue in checkout modal)

release 4.6.4

---

examples/react/src/components/Connected.tsx
packages/checkout/src/contexts/SelectPaymentModal.ts
packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx

added support for custom credit card providers for singularity SDK integration on eden mart

added custom provider callback

---

packages/checkout/src/views/TransactionSuccess.tsx

removed duplicated onSuccess function call

remove duplicated onSuccess function call

---

packages/checkout/src/contexts/CheckoutModal.ts
packages/checkout/src/contexts/SelectPaymentModal.ts
packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx
packages/checkout/src/views/PaymentSelection/index.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx

Added a supplementary fields parameter for the kit checkout modal so that the marketplace team can add in additional fields.

supplementary fields for analytics

---

.husky/pre-commit
eslint.config.mjs
packages/checkout/src/hooks/useMarketplaceClient.ts
packages/checkout/src/views/AddFunds.tsx
packages/checkout/src/views/PaymentSelection/index.tsx
packages/connect/src/connectors/ecosystem/provider.ts
packages/connect/src/connectors/ecosystem/providerTransport.ts
packages/connect/src/hooks/useWaasEmailAuth.ts

I expanded the linter to check react hooks more carefully, to debug a problem I was having [here](https://github.com/0xsequence-demos/primary-sale-1155-boilerplate/pull/18)
Here's the output:
```
/Users/tomaszdysinski/Repositories/horizon/0xsequence/web-sdk/packages/checkout/src/hooks/useMarketplaceClient.ts
16:35  error  React Hook "useEnvironmentContext" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
/Users/tomaszdysinski/Repositories/horizon/0xsequence/web-sdk/packages/checkout/src/views/AddFunds.tsx
120:3  error  React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after …
```

debugging react hooks

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.0.7, containing approved spender address change

release 5.0.7

---

packages/hooks/src/hooks/Combination/useGetSwapPrices.ts

Better error/unexpected values handling in useSwapPrices which fixes the issue of the query attempting to retry infinitely.

better error/unexpected values handling in useSwapPrices

---

packages/checkout/src/views/AddFunds.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx

force the referrer policy for transak's iframe

force referrer policy in transak

---

packages/checkout/src/views/AddFunds.tsx
packages/checkout/src/views/PaymentSelection/index.tsx

Filter out the transak credit card provider options when the configuration is not present (ie. no Transak contract id provided)

filter valid credit card providers for transak

---

packages/connect/src/components/Connect/Connect.tsx

Fixes descriptive socials not properly showing in rows

fixed descriptive socials showing in rows

---

examples/react/src/config.ts
packages/connect/src/styles.ts
packages/immutable-connector/README.md

Added parameter to passport instance configuration alongside documentation so that new wallets work properly.

passport instance config for immutable

---

examples/next/CHANGELOG.md
examples/react/CHANGELOG.md
packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.1.0

---

examples/react/src/config.ts

enables the immutable connector in the web-sdk demo

enable the immutable connector in the web-sdk demo

---

examples/react/src/config.ts
packages/immutable-connector/README.md

fixes issues in which logging out of immutable redirects to localhost

fix logging out of immutable redirect to localhost

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.1.1

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.2.3, including lifi update for swaps

release 5.2.3

---

README.md
examples/react/src/config.ts
packages/checkout/src/components/SequenceCheckoutProvider/SequenceCheckoutProvider.tsx
packages/connect/README.md
packages/connect/src/components/SequenceConnectProvider/SequenceConnectProvider.tsx
packages/connect/src/components/ShadowRoot/ShadowRoot.tsx
packages/connect/src/styles.ts
packages/connect/src/types.ts
packages/wallet-widget/src/components/SequenceWalletProvider/SequenceWalletProvider.tsx

`customCSS` ConnectOption for injecting custom css within the shadow dom

Adding custom injected css

---

examples/react/src/components/Connected.tsx
packages/checkout/src/contexts/CheckoutModal.ts
packages/checkout/src/hooks/useCheckoutUI/useCreditCardPayment.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx
packages/connect/src/styles.ts

transakApiKey field now made optional and using the global transak api key if none other is specified

made the transakApiKey field of transakConfig optional

---

packages/checkout/package.json
packages/connect/package.json
packages/connect/src/styles.ts
packages/hooks/package.json
packages/immutable-connector/package.json
packages/wallet-widget/package.json

Fix for running the web-sdk locally

dev mode fix

---

examples/react/src/components/Connected.tsx
packages/checkout/src/hooks/useERC1155SaleContractCheckout.ts

fixed effective price used by sales contract

effective sale price fix

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

releae 5.3.1, which includes a fix for the calcualtion of the effective price of a sale contract

release 5.3.1

---

packages/checkout/src/views/PaymentSelection/index.tsx

- added collection address to checkout events

added collectible address to checkout events

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.3.2
- handle case of geoblocked waas connections
- extra fields added to analytics

web-sdk release 5.3.2

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

-includes fix making the tokenId field of collectible optional to support ERC-721 sales contracts

release 5.3.3

---

packages/checkout/src/views/Checkout/PaymentMethodSelect/OrderSummary/index.tsx
packages/checkout/src/views/Checkout/PaymentMethodSelect/PayWithCrypto/index.tsx
packages/checkout/src/views/Checkout/PaymentMethodSelect/index.tsx
packages/connect/src/styles.ts

Added state for items priced at 0. The FREE tag is displayed in that scenario

added state for orders priced at 0

---

packages/checkout/src/contexts/CheckoutModal.ts
packages/checkout/src/contexts/SelectPaymentModal.ts
packages/checkout/src/contexts/TransactionStatusModal.ts
packages/checkout/src/views/Checkout/PaymentMethodSelect/PayWithCrypto/index.tsx
packages/checkout/src/views/PendingCreditCardTransaction.tsx
packages/checkout/src/views/TransactionStatus/index.tsx
packages/connect/src/styles.ts

- Added ability to show optional action button in the confirmation modal

show optional action buttons in confirmation modal

---

examples/react/src/components/Connected.tsx
packages/checkout/README.md
packages/checkout/src/hooks/useSwapModal.ts
packages/connect/src/styles.ts

Ticket link: 
Removed all instances of the "Sequence Pay" branding from web-sdk

removed all instances of the sequence pay branding

---

packages/checkout/src/views/TransactionStatus/index.tsx
packages/connect/src/styles.ts

Ticket link: 
Added class to allow customization of action buttons in the transcation status modal

added class to enable the customization of sucess buttons

---

examples/react/src/config.ts
packages/connect/src/styles.ts

Ticket link: 
Added the sepolia network (used by the forte payment flow) to react demo so that the crypto checkout flow also works

added sepolia network to react demo

---

packages/checkout/src/api/data.ts
packages/checkout/src/views/PendingCreditCardTransaction.tsx
packages/connect/src/styles.ts

Ticket link: 
Better default values for currencies used by forte so etherlink can use the correct symbols

forte currency default

---

examples/react/src/config.ts
packages/connect/src/styles.ts

Ticket link: 
Added sepolia network to demo in the waas config. It was added only to the universal wallet previously and it causes an undefined error for the wallet.

added sepolia network to waas

---

examples/react/src/utils/checkout.ts
packages/checkout/src/components/SequenceCheckoutProvider/ForteController.tsx
packages/checkout/src/contexts/CheckoutModal.ts

Ticket link: 
Improved onClose callback for the forte integration so that it may include more events. All the events are mutually exclusive.

improved onClose callback for forte

---

packages/checkout/src/views/Swap/index.tsx

Ticket link: 
fix for undefined wallet client

fix for undefined wallet client

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/checkout/src/views/Swap/index.tsx
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.3.17

---

packages/checkout/CHANGELOG.md
packages/checkout/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/constants/version.ts
packages/connect/src/styles.ts
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/immutable-connector/CHANGELOG.md
packages/immutable-connector/package.json
packages/wallet-widget/CHANGELOG.md
packages/wallet-widget/package.json

release 5.3.20
