0xsequence/web-sdk

- examples/components/package.json
- examples/components/src/Header.tsx
- examples/next/src/app/components/Connected.tsx
- examples/react/src/components/Connected.tsx
- pnpm-lock.yaml
> Example Header includes NetworkSelect and AccountMenu with Signout button

- examples/next/CHANGELOG.md
- examples/next/package.json
- examples/react/CHANGELOG.md
- examples/react/package.json
- packages/checkout/CHANGELOG.md
- packages/checkout/package.json
- packages/checkout/src/hooks/useSardineClientToken.ts
- packages/connectors/CHANGELOG.md
- packages/connectors/package.json
- packages/kit/CHANGELOG.md
- packages/kit/package.json
- packages/wallet/CHANGELOG.md
- packages/wallet/package.json
Fix issue causing the NFT checkout to refresh when switching tabs.
> fix sardine checkout refreshing when switching tabs + release 2.8.9

- packages/kit/src/components/Connect/ConnectWalletContent.tsx
- packages/kit/src/components/Connect/index.ts
- packages/kit/src/components/KitProvider/KitProvider.tsx
- packages/kit/src/index.ts
I exported the content here because we want to preview how the wallet will look on the Builder side without opening a modal. This way, it will be very simple for us.
Ticket -> https://github.com/0xsequence/issue-tracker/issues/3081
> Export connect wallet content to preview on Builder

- README.md
- packages/checkout/src/shared/components/KitCheckoutProvider.tsx
- packages/kit/README.md
- packages/kit/package.json
- packages/kit/src/components/KitPreviewProvider/KitPreviewProvider.tsx
- packages/kit/src/components/KitProvider/KitProvider.tsx
- packages/wallet/src/shared/KitWalletProvider/index.tsx
- pnpm-lock.yaml
The design-system dependency has been moved out of kit so as to increase compatibility with the `pages` router in nextJS
> Moved design-system dependency out of kit

- README.md
- examples/next/src/app/layout.tsx
- examples/react/src/App.tsx
- package.json
- packages/kit/README.md
- packages/kit/package.json
- pnpm-lock.yaml
Currently we require integrators to add @0xsequence/design-system as a peer dependency so that they may import @0xsequence/design-system/styles.css into their project and allow their unique bundler setup to take over including of the css file in their project.
But if we add design-system as a regular dependency of kit we can rexport the styles.css to make this simpler.
```
"exports": {
".": {
"types": "./dist/types/index.d.ts",
"require": "./dist/cjs/index.js",
"import": "./dist/esm/index.js",
"default": "./dist/esm/index.js"
},
"./styles.css": "./node_modules/@0xsequence/design-system/dist/style.css"
},
```
before:
```ts
import from '@0xsequence/design-system/styles.css'
```
after:
```ts
import from '@0sequence/kit/styles.css`
```
Since each project will already have the kit package as a …
> Re export the design system styles.css from kit to reduce extra peer dependency on integrators

- packages/kit/src/components/Connect/ConnectWalletContent.tsx
- packages/kit/src/components/KitPreviewProvider/KitPreviewProvider.tsx
We are using this component on the builder side for wallet customization, and since it's not an actual modal, the ModalPrimitive.Title component is causing issues.
> Fix broken preview

- examples/react/src/components/Connected.tsx
- packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx
- packages/checkout/src/views/PaymentSelection/index.tsx
- packages/checkout/src/views/Swap/index.tsx
- packages/checkout/src/views/TransactionStatus/index.tsx
- packages/kit/src/hooks/data.ts
Fixes related to sequence pay:
1: Clearer details related to the Swap modal in the demo
2: in the swap modal, the main currency defaults to being hidden
3: Simplified management of the zero address with the swap API (0x uses a different addres for the native currency the 0x000..)
4: Fixed the public client to the desired chain id to avoir network switching issues
> Sequence pay fixes

- packages/checkout/src/views/TransactionStatus/index.tsx
Fixed onSuccess callback not working with successful transactions in Sequence Pay
> fixed onSuccess callback for transaction status modal

- packages/checkout/src/utils/transak.ts
Added immutable zkevm as part of the default networks for transak fiat onramp
> immutable zkevm as part of default networks for transak

- packages/wallet/src/views/SendCollectible.tsx
Fix issues which prevents ERC-1155 to be transferred from the inventory.
> Transferring ERC-1155 fix from inventory

- examples/next/package.json
- examples/react/package.json
- package.json
- packages/checkout/package.json
- packages/kit/package.json
- packages/kit/src/components/Connect/Connect.tsx
- packages/kit/src/components/KitProvider/KitProvider.tsx
- packages/kit/src/config/defaultConnectors.ts
- packages/kit/src/connectors/coinbaseWallet/CoinbaseWalletLogo.tsx
- packages/kit/src/connectors/metaMask/MetaMaskLogo.tsx
- packages/kit/src/connectors/metaMask/index.ts
- packages/kit/src/connectors/metaMask/metaMask.ts
- packages/wallet/package.json
- pnpm-lock.yaml
This adds metamask connector that uses the sdk which supports connecting via mobile app even if the extension is not available. It is added similar to coinbase wallet one.
you can test on https://metamask-connector-test.pages.dev/
Previews:
on desktop, connection via mobile app:
https://github.com/user-attachments/assets/bc33fb7d-db1d-4c1b-b3d3-3cdbd6129b83
on mobile, via redirect:
https://github.com/user-attachments/assets/00554240-b910-4b03-8d7c-b5e52bb15108
> Metamask connector

- packages/checkout/src/views/PaymentSelection/index.tsx
Faster native token option loading in Sequence Checkout when it is the target contract's currency.
> native token option faster loading in checkout

- packages/checkout/src/views/PaymentSelection/PayWithCrypto/CryptoOption.tsx
- packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx
Improved display of Swap Options in checkout modal by removing the double scrollbar in favor of show more button,
https://www.loom.com/share/03e14e95fb194ac8a39f8096620266df?sid=9ab2858d-5d3a-40c9-b608-70c3edc9666c
> Improved display of Swap Options in checkout modal

- packages/wallet/src/views/Home/components/AssetSummary/CoinTile/CoinTileContent.tsx
Fixed issue that of content of coin tile overflowing which caused issue with Eden online's marketplace.
> fixed coin images overflowing

- packages/checkout/src/views/TransactionStatus/index.tsx
The rootUrl already contains an ending `/`
> Remove extra slash in blockexporer url

- examples/next/src/app/components/Connected.tsx
- examples/react/src/components/Connected.tsx
- packages/react-checkout/README.md
- packages/react-connect/src/hooks/useWaasFeeOptions.ts
- packages/react-connect/src/utils/txnDecoding.ts
- packages/react-wallet/src/components/FeeOptionSelector.tsx
- packages/react-wallet/src/views/SendCoin.tsx
- packages/react-wallet/src/views/SendCollectible.tsx
wagmi is viem based, and sequence is ethers based. This makes it difficult to completely remove ethers completely, but we can reduce the surface area by using viem functions whenever possible. This should have ease an eventual transition off of ethers.
Before: ethers was used **101** times across **28** files.
After: ethers is still used **26** times in **5** files.
> Reduce ethers

- packages/checkout/src/components/SequenceCheckoutProvider/SequenceCheckoutProvider.tsx
- packages/checkout/src/views/AddFunds.tsx
- packages/checkout/src/views/PaymentSelection/FundWithFiat.tsx
- packages/checkout/src/views/PaymentSelection/index.tsx
- packages/checkout/src/views/PendingCreditCardTransaction.tsx
- Fixed messages not being received in transak/sardine iframes. It seems the newly added shadowRoot negatively impacted the DOM query. DOM querying was replaced by using refs to track source of the message
- Made the iframes slightly larger to fit the recommended size from Transak
- Fixed the the onClose callback being called when going from the checkout modal to the funding with credit card modal
> Fixed messages not received in iframes + other fixes

- packages/connect/src/components/CryptoOption.tsx
- packages/connect/src/styles.ts
Hide the selector when funds are insufficient in checkout modal
> hide select indicator when insufficient funds

- examples/react/src/components/Connected.tsx
- packages/connect/src/styles.ts
Added ability to select credit card provider based on query strings
> query strings credit card provider

- packages/checkout/src/views/PaymentSelection/PayWithCrypto/index.tsx
- packages/checkout/src/views/PaymentSelection/index.tsx
- packages/connect/src/styles.ts
- packages/hooks/src/types/hooks.ts
Ignore swap routes state for direct currency payment for marketplace contracts.
Remove extra API call to swap routes and pass routes through props.
Added a retry limit of 3.
> fix: checkout purchase modal

- packages/connect/src/hooks/useStorage.ts
- packages/hooks/README.md
- packages/hooks/src/hooks/API/useGetCoinPrices.ts
- packages/hooks/src/hooks/API/useGetCollectiblePrices.ts
- packages/hooks/src/hooks/API/useGetExchangeRate.ts
- packages/hooks/src/hooks/Combination/useGetSwapQuote.ts
- packages/hooks/src/hooks/Combination/useGetSwapRoutes.ts
- packages/hooks/src/hooks/Indexer/useGetTransactionHistory.ts
- packages/hooks/src/hooks/Indexer/useGetTransactionHistorySummary.ts
- packages/hooks/src/hooks/IndexerGateway/useGetNativeTokenBalance.ts
- packages/hooks/src/hooks/IndexerGateway/useGetSingleTokenBalance.ts
- packages/hooks/src/hooks/IndexerGateway/useGetTokenBalancesByContract.ts
- packages/hooks/src/hooks/Metadata/useGetContractInfo.ts
- packages/hooks/src/hooks/Metadata/useGetMultipleContractsInfo.ts
- packages/hooks/src/hooks/Metadata/useGetTokenMetadata.ts
- packages/wallet-widget/src/views/SwapCoin/SwapList.tsx
Fix for problem related to infinite retries. We are now avoiding using `retry: true` for the react query hooks since that will cause failed http request to retry infinitely.
> fix for infinite retries

- examples/react/src/components/Connected.tsx
- examples/react/src/constants/erc721-sale-contract.ts
- packages/checkout/src/contexts/SelectPaymentModal.ts
- packages/checkout/src/contexts/TransactionStatusModal.ts
- packages/checkout/src/hooks/useCheckoutUI/index.tsx
- packages/checkout/src/hooks/useCheckoutUI/useCreditCardPayment.tsx
- packages/checkout/src/hooks/useERC1155SaleContractCheckout.ts
- packages/checkout/src/views/PaymentSelection/OrderSummary/index.tsx
- packages/checkout/src/views/PaymentSelection/PayWithCreditCard/index.tsx
- packages/checkout/src/views/PaymentSelection/index.tsx
- packages/checkout/src/views/TransactionStatus/index.tsx
- packages/connect/src/styles.ts
handle undefined token ids for the purpose of supporting erc-721 sale contracts. The collection image will be used instead if there are not token ids.
> handle undefined token ids for erc-721 sale contracts

- examples/next/package.json
- examples/react/package.json
- packages/connect/package.json
- packages/connect/src/components/ShadowRoot/ShadowRoot.tsx
- packages/connect/src/styleProperties.ts
- packages/connect/src/styles.ts
- pnpm-lock.yaml
https://github.com/tailwindlabs/tailwindcss/issues/15005
Injects --tw vars to the end of the style sheet without the @supports which prevents the vars from being created.
> Fix tailwind4 properties

- packages/checkout/src/views/Checkout/PaymentMethodSelect/PayWithCrypto/index.tsx
- packages/checkout/src/views/Checkout/PaymentMethodSelect/index.tsx
Ticket link: 
- added clearer loading state when a transaction is in progress
- removed the tabs in checkout if only a single option is selected
> loading state, tab removed if only 1 option

- packages/connect/src/hooks/useWaasFeeOptions.ts
- packages/connect/src/styles.ts
Ticket link: 
After I rejected a pending fee option, the hook’s state reset, but `pendingFeeOptionConfirmation` was still returning fee options. It turns out resetting `sharedPendingConfirmation` was missing.
> Clear pending confirmation state in useWaasFeeOptions hook.

- examples/react/src/config.ts
- packages/checkout/src/views/Checkout/PaymentMethodSelect/PayWithCrypto/index.tsx
- packages/checkout/src/views/Checkout/PaymentMethodSelect/index.tsx
- packages/connect/src/styles.ts
This removes the chainId param from useWalletClient in checkout pay-with-crypto. The chainId param is just a filter and causes the walletClient to be undefined if there is a chain mismatch. The chain switching is handled by a switch chain further down in the code
> Fix undefined wallet client in checkout

- packages/checkout/src/views/Checkout/PaymentMethodSelect/PayWithCrypto/index.tsx
* Updated the logic for determining insufficient balance to handle undefined tokenBalance cases.
```
const tokenBalance = tokenBalancesData?.pages?.[0]?.balances?.find(balance =>
compareAddress(balance.contractAddress, selectedCurrency.address)
)
```
if `tokenBalancesData?.pages?.[0]?.balances` is an empty array, `tokenBalance` goes undefined, we don't check this for `isInsufficientBalance`.
Ticket link: https://github.com/0xsequence-demos/fusionpoint-issue-tracker/issues/40
> Refactor insufficient balance check in PayWithCrypto component

- examples/next/src/app/components/Connected.tsx
- examples/react/src/components/Connected.tsx
- packages/checkout/src/views/TransactionStatus/index.tsx
- packages/connect/src/styles.ts
Ticket link: 
disable scientific notation for prices in transaction status modal
> disable scientific notation for prices in the transaction status modal

- packages/connect/src/styles.ts
- packages/connect/src/utils/transactions.ts
Ticket link: 
Add retry for transaction receipt fetch
> tx receipt retry
